# Generated by Django 3.0.2 on 2020-03-12 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Properties', '0001_initial'),
        ('ServiceProvider', '0001_initial'),
        ('Appliances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=300)),
                ('serviceCategory', models.CharField(default='unknown', max_length=50)),
                ('serviceType', models.CharField(max_length=100, null=True)),
                ('client', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('serviceDate', models.DateTimeField()),
                ('appFixed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appliances.Appliance')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Properties.Property')),
                ('serviceCompany', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ServiceProvider.ServiceProvider')),
            ],
        ),
    ]
