# Generated by Django 3.0.2 on 2020-05-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceRequest', '0002_auto_20200514_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='poc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='pocName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
