# Generated by Django 3.0.2 on 2020-02-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rooId',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
