# Generated by Django 3.0 on 2020-01-14 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('SLID', models.IntegerField()),
                ('numBath', models.IntegerField()),
                ('numBed', models.IntegerField()),
                ('maxTenants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyManager',
            fields=[
                ('propertyManagerId', models.AutoField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenantId', models.AutoField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('pmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.PropertyManager')),
                ('propId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.PropertyManager'),
        ),
    ]
