# Generated by Django 3.0.2 on 2020-02-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyManagers', '0002_auto_20200225_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanager',
            name='rooToken',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
