# Generated by Django 3.0.2 on 2020-05-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0002_preferredproviders'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='certified',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='logo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='rate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='contractLic',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='email',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='phoneNum',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
