# Generated by Django 3.0.2 on 2020-05-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0003_auto_20200513_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='rooId',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
