# Generated by Django 3.0.2 on 2020-01-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanager',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
