# Generated by Django 3.0.2 on 2020-01-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200120_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='phone',
        ),
    ]
