# Generated by Django 3.0.2 on 2020-01-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_tenant_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='SLID',
        ),
        migrations.RemoveField(
            model_name='propertymanager',
            name='phone',
        ),
        migrations.AlterField(
            model_name='property',
            name='numBath',
            field=models.FloatField(),
        ),
    ]
