# Generated by Django 3.0.2 on 2020-05-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='phoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
