# Generated by Django 3.0.2 on 2020-05-31 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyManagers', '0001_initial'),
        ('Tenants', '0002_tenant_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='pm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PropertyManagers.PropertyManager'),
        ),
    ]
