# Generated by Django 3.0.2 on 2020-05-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='rooAppId',
            new_name='apikey',
        ),
    ]
