# Generated by Django 3.0.2 on 2020-05-14 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyManagers', '0001_initial'),
        ('Tenants', '0002_tenant_phonenumber'),
        ('Tools', '0002_auto_20200513_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('isPm', models.BooleanField(default=False, null=True)),
                ('isTenant', models.BooleanField(default=False, null=True)),
                ('pm', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PropertyManagers.PropertyManager')),
                ('tenant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tenants.Tenant')),
            ],
        ),
    ]
