# Generated by Django 3.0.2 on 2020-05-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0003_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='rooPairsToken',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
