# Generated by Django 3.0.2 on 2020-05-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0007_auto_20200531_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='pmBool',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='tenantBool',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
