# Generated by Django 3.0.2 on 2020-02-25 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Properties', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='unspecified', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('modelNum', models.IntegerField(null=True)),
                ('serialNum', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('rooAppId', models.IntegerField(null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Properties.Property')),
            ],
        ),
    ]
