# Generated by Django 3.0.2 on 2020-03-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appliances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='rooAppId',
            field=models.CharField(default='hello', max_length=10),
            preserve_default=False,
        ),
    ]
